Name: Tests

on: [push, pull_request]

env:
    NODE_VERSION: 16

jobs:
    tests:
        matrix:
            os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        name: Run tests on ${{ matrix.os }} with Node ${{ env.NODE_VERSION }}
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install node dependencies
              run: yarn install

            - name: Bundle files
              run: yarn bundle
              env:
                  NODE_ENV: production
