name: Tests

on:
    push:
        tags:
            - "*"

jobs:
    tests:
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        name: Run tests on ${{ matrix.os }}
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install node dependencies
              run: yarn install
              env:
                  NODE_ENV: development

            - name: Lint files
              run: yarn lint

            - name: Run tests
              run: yarn test

            - name: Bundle files
              run: yarn bundle
              env:
                  NODE_ENV: production

            - name: Package and publish app
              run: yarn package:publish
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
