name: Build

on: [push, pull_request]

jobs:
    tests:
        strategy:
            matrix:
                os: [macos-12, windows-2022, ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        name: Run tests on ${{ matrix.os }}
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install node dependencies
              run: yarn install
              env:
                  NODE_ENV: development

            - name: Lint files
              run: yarn lint

            - name: Run tests
              run: yarn test

            - name: Bundle files
              run: yarn bundle
              env:
                  NODE_ENV: production

            - name: Package and publish app
              if: startsWith(github.ref, 'refs/tags')
              run: yarn package:publish
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
