name: Tests

on: [push, pull_request]

jobs:
    tests:
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        name: Run tests on ${{ matrix.os }}
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install node dependencies
              run: yarn install

            - name: Bundle files
              run: yarn bundle
              env:
                  NODE_ENV: production
